### ISSUE TITLE
Temperature precision

### ISSUE THREAD

**Issue by oiv** [balda/ruuvitag-discovery#1]
Sometimes the temperature has way too many digits at least in home-assistant mqtt

In HA
RuuviTag Otto Temperature
26.115000000000002 °C

MQTT message
homeassistant/sensor/ffxxxxxxxxxx/temperature/state 26.115000000000002
homeassistant/sensor/ffxxxxxxxxxx/temperature/attributes {"RuuviTag":"ffxxxxxxxxxx","Measure":"Temperature","Unit":"°C"}

Tag has latest ruuvi firmware.

**Comment by balda** [comment]
Thanks. It's fixed in `0.1.10`.

Precision for each measure is defined in `https://github.com/balda/ruuvitag-discovery/blob/master/dict/measures.js` (`accuracy` field).
