### ISSUE TITLE
Column headings for Period and Last Seen should not include secs - enhancement 

### ISSUE THREAD

**Issue by DG12** [balda/ruuvitag-discovery#10]
The Column headings (i.e. title ) for Period and Last Seen should not include secs
as it makes the column unnecessarily wide

js/cols.js

```
is: title: `Period (sec)`,
SB: title: `Period`,
```

```
is: title: `Last seen (sec)`,
SB: title: `Last seen`,
```

Thanks again for a great program

**Comment by balda** [comment]
You're right: that will be fixed in next release (units will be displayed in a tooltip on rollover on a column header).

**Comment by balda** [comment]
Done in release `0.2.0`
