### ISSUE TITLE
humidity must report min(humidity,100.01) or '--' or '  '

### ISSUE THREAD

**Issue by DG12** [balda/ruuvitag-discovery#11]
Some versions of the firmware for the ruuviTags do not artificially cap the humidity at 100% when the BME280's humidity sensor returns invalid values.
The reporting application (ruuvitag-discovery) needs to report  either min(humidity,100.01) permitting the observer to understand that the sensor reported invalid values OR preferably  suppress the values altogether with a placeholder or space (or NULL)

**Comment by ojousima** [comment]
It's also possible that BME280 has positive offset such as +3%. Then 100 % real would get reported as 103 %, so capping at 100 % would be a reasonable option. There's a special value for invalid, 0 % on RAWv1 / data format 3 and uint16_t max on RAWv2 / data format 5.

**Comment by balda** [comment]
Good remark, thanks. I add it on my roadmap ;)

**Comment by DG12** [comment]
@ojousima regarding BME280 offset:  isn't the offset in the mobile phone application ?
ruuvitar-discovery takes packets directly from the tag. Is there an offset inn the data from the tag?

**Comment by balda** [comment]
Done in release 0.2.6: you can add custom measures with math expressions that cap and/or offset values (so raw data is still kept). You can even make a condition on data format if needed (I added some examples).
