### ISSUE TITLE
Ruuvitag-discovery restart needed after ha restart

### ISSUE THREAD

**Issue by oiv** [balda/ruuvitag-discovery#12]
It seems that after a home-assistant restart is done I need to do a restart for ruuvitag-discovery even when it is marked to start automatically. 

Looking MQTT messages shows that ha only gets the config messages for the first tag it finds. Later it sends the values correctly for all tags. But since without the config ha shows the state as unavailable. After a restart it sends the config messages for all (three) tags it finds. I believe home assistant needs the config messages after every restart..( which I don't understand why... :-D )

I am running ruuvitag-discovery addon 0.1.11 and Home Assistant 0.111.4 on a Raspberry Pi 3B. HassOS 4.10. Only target is Home Assistant (MQTT) with three ruuvitags.

[addonrestart.log](https://github.com/balda/ruuvitag-discovery/files/4850031/addonrestart.log)
[harestart.log](https://github.com/balda/ruuvitag-discovery/files/4850033/harestart.log)

**Comment by balda** [comment]
You are right. I have already noticed this bug, but I have not yet had time to investigate.
As it is quite painful to have to restart the add-on with each HA upgrade, I will try not to let this issue drag too much.
And thanks for the logs ;)

**Comment by balda** [comment]
Should be fixed in `0.1.12` ;)

**Comment by balda** [comment]
It's not fixed and Home Assistant seems to have changed something ...
```
ERROR (SyncWorker_6) [supervisor.docker.addon] Can't build 5069d20e/armv7-addon-ruuvitag-discovery:0.1.12: The command '/bin/ash -o pipefail -c apk add --no-cache npm libusb-dev bluez-dev linux-headers eudev-dev build-base python git' returned a non-zero code: 1
```
I must investigate why...

**Comment by balda** [comment]
It should be OK with `0.1.13`.
RuuviTags are "presented" every 30 seconds. So you shouldn't wait more than 30 seconds to see the measurements after an update :-)
