### ISSUE TITLE
Newly configured tags won't get their measurements sent to mqtt

### ISSUE THREAD

**Issue by thjr** [balda/ruuvitag-discovery#15]
If you configure more tags, their measurements won't be sent to mqtt.

You have to export configuration, uninstall, install again and then import the same configuration.

**Comment by balda** [comment]
I have never encountered this bug. I will do more extensive testing to try to reproduce it.

**Comment by vilpponen** [comment]
I am having this same issue. The measurement column is "n/a" in the targets list. I'm trying to only send the temperature value over. I'm also not seeing any connections on my broker's side from ruuvitag-discovery. However, I have only 1 ruuvi tag in the list, I can't get that sending data either.

**Comment by balda** [comment]
In release `0.2.0`, a lot of code has been rewritten ... hope this fixes your problems.
If not, could you paste your config? (replace private data like passwords by some "XXX")

**Comment by niirvana-git** [comment]
Same issue here also with the latest version. No data is send nor visible in home assitant.

**Comment by balda** [comment]
I think I found why it's buggy ... working on it

**Comment by niirvana-git** [comment]
Great! 👍

**Comment by balda** [comment]
New fresh release `0.2.3`. I made some bugfixes. I hope this will solve your problems.

And I added config options to see more server logs (the doc is not yet up to date, but can be changed in UI). It might help if you're still having trouble.

**Comment by vilpponen** [comment]
Thanks @balda - my issue got fixed in 0.2.0 already. Apologies for the delayed feedback. Great job with the app so far, thanks!

**Comment by balda** [comment]
@thjr : as the add-on seems to work fine for @vilpponen and @niirvana-git , can you confirm (or not) that's the same for you? So issue can be closed (or I must dig deeper to solve the problem).

**Comment by thjr** [comment]
this seemed to work, I tested with with API as a target
