### ISSUE TITLE
Addon installation fails on docker Hassio

### ISSUE THREAD

**Issue by petait** [balda/ruuvitag-discovery#19]
Not possible to install through addon store. Gives following error message on HASS.io running in docker on Synology NAS:

_"Failed to install addon
The command '/bin/ash -o pipefail -c apk add --no-cache npm libusb-dev bluez-dev linux-headers eudev-dev build-base python git' returned a non-zero code: 61"_

From Supervisor log:

"20-11-22 09:59:17 INFO (SyncWorker_2) [supervisor.docker.addon] Starting build for 5069d20e/amd64-addon-ruuvitag-discovery:0.1.13
20-11-22 09:59:25 ERROR (SyncWorker_2) [supervisor.docker.addon] Can't build 5069d20e/amd64-addon-ruuvitag-discovery:0.1.13: The command '/bin/ash -o pipefail -c apk add --no-cache npm libusb-dev bluez-dev linux-headers eudev-dev build-base python git' returned a non-zero code: 61
20-11-22 09:59:25 ERROR (SyncWorker_2) [supervisor.docker.addon] Build log: 
Step 1/23 : ARG BUILD_FROM

Step 2/23 : FROM ${BUILD_FROM}

 ---> e3299fbb2f75

Step 3/23 : ENV LANG C.UTF-8

 ---> Using cache

 ---> d3b551c3dcb1

Step 4/23 : RUN apk add --no-cache npm libusb-dev bluez-dev linux-headers eudev-dev build-base python git

 ---> Running in 61938c4db919

fetch http://dl-cdn.alpinelinux.org/alpine/v3.11/main/x86_64/APKINDEX.tar.gz

fetch http://dl-cdn.alpinelinux.org/alpine/v3.11/community/x86_64/APKINDEX.tar.gz

fetch http://dl-cdn.alpinelinux.org/alpine/edge/main/x86_64/APKINDEX.tar.gz

fetch http://dl-cdn.alpinelinux.org/alpine/edge/community/x86_64/APKINDEX.tar.gz

fetch http://dl-cdn.alpinelinux.org/alpine/edge/testing/x86_64/APKINDEX.tar.gz

ERROR: unsatisfiable constraints:

  musl-1.1.24-r2:
    breaks: musl-dev-1.1.24-r3[musl=1.1.24-r3]
    satisfies: world[musl=1.1.24-r2]
               apk-tools-2.10.4-r3[so:libc.musl-x86_64.so.1]
               kmod-26-r0[so:libc.musl-x86_64.so.1]
               pkgconf-1.6.3-r0[so:libc.musl-x86_64.so.1]
               libblkid-2.34-r1[so:libc.musl-x86_64.so.1]
               gcc-9.3.0-r0[so:libc.musl-x86_64.so.1]
               g++-9.3.0-r0[so:libc.musl-x86_64.so.1]
               tzdata-2019c-r0[so:libc.musl-x86_64.so.1]
               bash-5.0.11-r1[so:libc.musl-x86_64.so.1]
               ca-certificates-20191127-r1[so:libc.musl-x86_64.so.1]
               eudev-3.2.9-r1[so:libc.musl-x86_64.so.1]
               libusb-1.0.23-r0[so:libc.musl-x86_64.so.1]
               busybox-1.31.1-r9[so:libc.musl-x86_64.so.1]
               binutils-2.33.1-r0[so:libc.musl-x86_64.so.1]
               sqlite-libs-3.30.1-r2[so:libc.musl-x86_64.so.1]
               curl-7.67.0-r0[so:libc.musl-x86_64.so.1]
               eudev-libs-3.2.9-r1[so:libc.musl-x86_64.so.1]
               libuv-1.34.0-r0[so:libc.musl-x86_64.so.1]
               ncurses-libs-6.1_p20200118-r2[so:libc.musl-x86_64.so.1]
               expat-2.2.9-r1[so:libc.musl-x86_64.so.1]
               git-2.24.3-r0[so:libc.musl-x86_64.so.1]
               musl-utils-1.1.24-r2[so:libc.musl-x86_64.so.1]
               nghttp2-libs-1.40.0-r0[so:libc.musl-x86_64.so.1]
               bluez-libs-5.52-r1[so:libc.musl-x86_64.so.1]
               nodejs-12.15.0-r1[so:libc.musl-x86_64.so.1]
               gdbm-1.13-r1[so:libc.musl-x86_64.so.1]
               python2-2.7.18-r0[so:libc.musl-x86_64.so.1]
               libstdc++-9.3.0-r0[so:libc.musl-x86_64.so.1]
               libbz2-1.0.8-r1[so:libc.musl-x86_64.so.1]
               file-5.37-r1[so:libc.musl-x86_64.so.1]
               isl-0.18-r0[so:libc.musl-x86_64.so.1]
               libcurl-7.67.0-r0[so:libc.musl-x86_64.so.1]
               mpc1-1.1.0-r1[so:libc.musl-x86_64.so.1]
               libmagic-5.37-r1[so:libc.musl-x86_64.so.1]
               oniguruma-6.9.4-r0[so:libc.musl-x86_64.so.1]
               libffi-3.2.1-r6[so:libc.musl-x86_64.so.1]
               zlib-1.2.11-r3[so:libc.musl-x86_64.so.1]
               libgomp-9.3.0-r0[so:libc.musl-x86_64.so.1]
               readline-8.0.1-r0[so:libc.musl-x86_64.so.1]
               make-4.2.1-r2[so:libc.musl-x86_64.so.1]
               libgcc-9.3.0-r0[so:libc.musl-x86_64.so.1]
               libssl1.1-1.1.1d-r3[so:libc.musl-x86_64.so.1]
               alpine-baselayout-3.2.0-r3[so:libc.musl-x86_64.so.1]
               libcrypto1.1-1.1.1d-r3[so:libc.musl-x86_64.so.1]
               libatomic-9.3.0-r0[so:libc.musl-x86_64.so.1]
               xz-libs-5.2.4-r0[so:libc.musl-x86_64.so.1]
               pcre2-10.34-r1[so:libc.musl-x86_64.so.1]
               c-ares-1.15.0-r0[so:libc.musl-x86_64.so.1]
               scanelf-1.2.4-r0[so:libc.musl-x86_64.so.1]
               gmp-6.1.2-r1[so:libc.musl-x86_64.so.1]
               jq-1.6-r0[so:libc.musl-x86_64.so.1]
               mpfr4-4.0.2-r1[so:libc.musl-x86_64.so.1]

Removing intermediate container 61938c4db919"

**Comment by petait** [comment]
By quick googling I found this: https://stackoverflow.com/questions/48892448/error-unsatisfiable-constraints-using-apk-in-dockerfile 
So problem is probably that "testing" repository. It's not counted as "stable" so it causes problems. Would it be possible to not to use it?

**Comment by nuuo90** [comment]
Hi petait,
I had same problem. Solution was to install RuuviTag Discovery manually.
I followed these instructions, 
First get NodeJS,: https://www.makersupplies.sg/blogs/tutorials/how-to-install-node-js-and-npm-on-the-raspberry-pi 
then followed this
https://github.com/balda/ruuvitag-discovery/issues/3 

Now I got it running. Just need to learn, how to use it.

**Comment by petait** [comment]
> Hi petait,
> I had same problem. Solution was to install RuuviTag Discovery manually.
> I followed these instructions,
> First get NodeJS,: https://www.makersupplies.sg/blogs/tutorials/how-to-install-node-js-and-npm-on-the-raspberry-pi
> then followed this
> #3
> 
> Now I got it running. Just need to learn, how to use it.

Hi Nuuo90,
Unfortunately that is not a solution for me as I'm using Hass.io on Synology in Docker. Only way would be to change that repository to a stable one.

**Comment by balda** [comment]
Thanks for reporting this bug. I'll try to take time this week-end to fix the build.
Home Assistant or docker image seems to have break something.

**Comment by balda** [comment]
Release `0.1.14` should fix the bug ;)

(`python` package was removed from alpine docker image, replaced by `python3`)

Build is working locally, but I havent tested it in Home Assistant. @petait I hope to have good news :)

**Comment by petait** [comment]
Thank you @balda ! It works like a charm now!
This add on is even better than I could have hoped for. So much thanks for it :)
