### ISSUE TITLE
Option to post values directly to home assistant

### ISSUE THREAD

**Issue by thjr** [balda/ruuvitag-discovery#2]
Hello

Can you add an option(a new target) to post values directly to home assistant.  This way I would not need to set up mqtt discovery.

**Comment by balda** [comment]
It's in the roadmap, but be aware that the Home Assistant api can't be used to add devices, only entities.
With MQTT discovery, we can add a device, then place it in an area.

**Comment by balda** [comment]
It's done in release `0.2.7` :)

I close the issue, but feel free to reopen if needed.
