### ISSUE TITLE
Detail page for a tag should include the user assigned name - enhancement 

### ISSUE THREAD

**Issue by DG12** [balda/ruuvitag-discovery#22]
Clicking on the (i) infos symbol presents a page with details of the tag. The top line which shows the (dynamic, temporary, ugly IMHO) ID  should also show the name.

**Comment by balda** [comment]
Good idea 👍

**Comment by DG12** [comment]
I would like to test  0.2.0 even before you are ready to publish it. :-)

**Comment by balda** [comment]
Released in `0.2.2`
