### ISSUE TITLE
0.2.0 version UI wont open due to insecure websocket 

### ISSUE THREAD

**Issue by pxFIN** [balda/ruuvitag-discovery#23]
When upgraded from 0.1.4 to 0.2.0 i cant open Ruuvitag Discovery UI anymore

I'm using HTTPS to access HA

From developer tools console(some parts removed from the message which should not be of importance):

Mixed Content: The page at 'https://(duckdns.org address removed)/hassio/ingress/(removed)' was loaded over HTTPS, but attempted to connect to the insecure WebSocket endpoint 'ws://duckdns address removed/api/hassio_ingress/(removed)'. This request has been blocked; this endpoint must be available over WSS.

App.svelte:11 Uncaught DOMException: Failed to construct 'WebSocket': An insecure WebSocket connection may not be initiated from a page loaded over HTTPS.

**Comment by balda** [comment]
It should be fixed with 0.2.1 (I experimented myself the bug :/)

**Comment by pxFIN** [comment]
That was fast and fix is working :)
