### ISSUE TITLE
web page references 2 .map files without version missing in distribution - 0.2.0

### ISSUE THREAD

**Issue by DG12** [balda/ruuvitag-discovery#24]
-rw-rw-r--@ 1 dgerman  staff  160392 Dec  6 11:59 bootstrap.4.5.3.min.css
-rw-rw-r--@ 1 dgerman  staff  369176 Dec  6 11:59 moment-with-locales.2.29.1.min.js

404 on http://127.0.0.1:8099/assets/moment-with-locales.min.js.map

and favicon.ico

**Comment by DG12** [comment]
I didn't want to create a separate issue, but, could you change the color from gray to black?

**Comment by balda** [comment]
The `.map` files are only usefull for debugging frontend code. Maybe I'll add them in the build (project is open-source, no reason to hide the code: it's public :) )

If you are curious, you can read this: https://css-tricks.com/should-i-use-source-maps-in-production/

**Comment by balda** [comment]
Missing `.map` are now included.
For the favicon, I must first make an app icon :)

For the color question, you can open a discussion (I activated this new github feature) as it's not really an issue, but a "style" choice.

So, I close this issue, create another for the icon and let you launch a "style" discussion ;)
