### ISSUE TITLE
3 tags showing as one through MQTT integration

### ISSUE THREAD

**Issue by petait** [balda/ruuvitag-discovery#29]
I have a really weird issue. Could be related to the new version of discovery (0.2.1) or not because I had only one ruuvitag before updating and now I have three. So can't know for sure. Anyway, I'm seeing only one device on the MQTT integration and it's contents are shifting between the three RuuviTags and values are always shown as Unknown.

When I click open the device list of the MQTT integration it randomly has one of the Ruuvis shown and if I click on that one the entities inside might be the same Ruuvi's or another one's. Also if I then click one of the entities it might show different Ruuvi's information. See below screenshot (I've named them Ruuvi-1, Ruuvi-2 and Ruuvi-3):

![image](https://user-images.githubusercontent.com/22786391/101531475-01094c00-399c-11eb-96f1-4f0c924ba72b.png)

Any ideas?

BR,
Petteri

**Comment by balda** [comment]
I agree, what a weird issue :/

If you only use MQTT integration with this addon, you can remove the MQTT integration to clean up and re-install the MQTT. It's not an elegant solution, but it should works.

Can you give me the hardware where Home Assistant run? On MacOS, for example, tag "ID" is obfucate and can change. But not on RaspberryPi (they never change). And Home Assistant need a fixed id. Maybe a lead?

**Comment by balda** [comment]
Release `0.2.3` fix some bugs that might be related to yours. Tell me if an update fix your problems.

**Comment by petait** [comment]
That fixed this! Everything is in order now. Thank you 👍

**Comment by balda** [comment]
Great, good news! :)
