### ISSUE TITLE
Addition install/usage documentation

### ISSUE THREAD

**Issue by DG12** [balda/ruuvitag-discovery#3]
Developers often forget that others (that want to accept their generous gifts) do not have the environment needed.

Please add to installation instructions:

1) Install Node.js the JavaScript runtime built on Chrome's V8 JavaScript engine from:
https://nodejs.org
2) Install npm the Node Package Manager from:
https://www.npmjs.com
3) Download https://github.com/balda/ruuvitag-discovery, move the zip to a directory of your choosing and unzip it (Mac OS double click in finder)
4) cd _discoveryDIrectory_
4) npm install # corejs usb
5) npm start # start the node server 
Expect to see:
<pre>
Start RuuviTag Discovery - v0.1.10
Start measures sampling every 10 seconds
Start web server on port 8099
Discover RuuviTag da798d1d39354757aa6f294e73617493
</pre>
6) Start a browser and retrieve the page at http://localhost:8099

A) Click on the [/] (edit symbol) and rename your tags.
B) refresh resets the last seen 
To stop use ^c. (SIGINT) and expect to see<pre>^CStop RuuviTag Discovery
Web server stopped</pre>

++++++++++++
Notice warning from npm:
npm WARN deprecated core-js@2.6.11: core-js@<3 is no longer maintained and not recommended for usage due to the number of issues. Please,  upgrade your dependencies to the actual version of core-js@3.

Thanks for a terrific system !

**Comment by DG12** [comment]
To upgrade an existing version be sure to run` npm install`

**Comment by balda** [comment]
Thanks! I will add it ;)

**Comment by balda** [comment]
Added to the doc :)

(npm is now installed with nodejs, so I don't added this step)
