### ISSUE TITLE
add MAC address to info for format 5

### ISSUE THREAD

**Issue by DG12** [balda/ruuvitag-discovery#4]
Please add MAC address to info (or even a column) for format 5 packets.

Thanks again

**Comment by balda** [comment]
It would be with pleasure, but the MAC address provided by the format 5 is not available in the nodejs library that I use.
I created an issue (pakastin/node-ruuvitag/issues/17).
If nobody makes a pull request for it, I'll take care of it when I have a little time available :)

**Comment by balda** [comment]
Done in release `0.1.11`
