### ISSUE TITLE
incorporate  alarms with limits - .0.2.6 - enhancement

### ISSUE THREAD

**Issue by DG12** [balda/ruuvitag-discovery#40]
For each device, for each sensor  4 limits could be available: low emergency, low warning, high warning, high emergency.

Consider a ruuviTag floating in a fresh water aquarium . A high warning could be a problem when the temperature is greater than 28C  and LessThan 30C which can happen if the water level is below the heater temperature sensor. A temperature greater than 30C is a real problem and must be corrected. If the temperature is below 20C but above 18C there may be a defective heater. If the temperature is below 18C you better do something or the fish are going to die!

See issue #38 where the central syslog server can issue a an email if text message if warning and a text message if emergency

**Comment by balda** [comment]
I don't think alarms are in the scope of this app. Too many channels.

But you can plug an alerting system on the target / database side. There are already a lot of programs that do that.

**Comment by DG12** [comment]
Yes indeed. I was thinking about that when I entered this,  but since discover was alreadying analyzing the pack I thought I'd ask.
