### ISSUE TITLE
Measurements sent to API target do not use custom names

### ISSUE THREAD

**Issue by thjr** [balda/ruuvitag-discovery#41]
I configured some tags with custom names for measurements.  They show up with default entity name (for example sensor.ruuvitag_c51a7c8f0996_temperature)

**Comment by balda** [comment]
You can now change entity ID in `0.2.9` (I added some help in the edit target panel). Re-open the issue if this is not the expected behavior.
Note that if you change entity ID, Home Assistant will consider the sensor as a new device.
