### ISSUE TITLE
MAC address display format improvment 

### ISSUE THREAD

**Issue by DG12** [balda/ruuvitag-discovery#6]
Formatting the MAC address with a fixed width font and preserving leading zero in each octet would be "nicer" 
For example:
version 1.11 shows 
D3:51:78:72:EC:F
which should be 
D3:51:78:72:EC:0F

![image](https://user-images.githubusercontent.com/2365961/83361089-041fe180-a354-11ea-80dd-bea4e91508fb.png)

Thanks again.

**Comment by DG12** [comment]
Revision to
dataformats/5.js
...
  robject.mac = [
    data[20].toString(16).toUpperCase().padStart(2,"0"),
    data[21].toString(16).toUpperCase().padStart(2,"0"),
    data[22].toString(16).toUpperCase().padStart(2,"0"),
    data[23].toString(16).toUpperCase().padStart(2,"0"),
    data[24].toString(16).toUpperCase().padStart(2,"0"),
    data[25].toString(16).toUpperCase().padStart(2,"0")
...

**Comment by balda** [comment]
Fixed in `node-ruuvitag` package.
You can rebuild your addon to update to last version if you are impatient. Or you can wait the next release ;)
