### ISSUE TITLE
battery (voltage) should be in volts not millivolts - enhancement 

### ISSUE THREAD

**Issue by DG12** [balda/ruuvitag-discovery#8]
dict/measures.js

field: `battery`,
    label: `Battery`,
    icon: `battery-bluetooth-variant`,
    unit: `V`,
    accuracy: 3,

node_modules/node-ruuvitag/dataformats/5.js
robject.battery = (    (powerInfo >>> 5) + 1600   ) /1000.;

node_modules/node-ruuvitag/dataformats/3.js
  robject.battery = battery/1000.;

**Comment by DG12** [comment]
Superseded by #18 remove battery voltage entirely.

**Comment by balda** [comment]
I close this issue in favour of #18.
