### ISSUE TITLE
auto refresh  - enhancement

### ISSUE THREAD

**Issue by DG12** [balda/ruuvitag-discovery#9]
Would like to add META HTTP-EQUIV="Refresh" CONTENT="30; URL=localhost:8099">

**Comment by balda** [comment]
Auto-refresh is in the roadmap. I'm working on a new version with websocket (live refresh :) )

**Comment by balda** [comment]
Rewrite is longer than expected, but it's planned in the new version (in fact, it's already coded).

**Comment by DG12** [comment]
Please include in the heading the time of last refresh and nnn minute ago.

**Comment by balda** [comment]
Done in release `0.2.0`
